/**/controller_manager:
  ros__parameters:
    update_rate: 80

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    controller_diff_drive:
      type: diff_drive_controller/DiffDriveController

/**/joint_state_broadcaster:
  ros__parameters:
    update_rate: 40

/**/controller_diff_drive:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    wheel_radius: 0.028
    wheel_separation: 0.112
    
    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    enable_odom_tf: true
    tf_frame_prefix: ""
    base_frame_id: "base_odom"

    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 0.5
    linear.x.min_velocity: -0.5
    linear.x.max_acceleration: 10.0
    linear.x.min_acceleration: -10.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: false
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 10.0
    angular.z.min_velocity: -10.0
    angular.z.max_acceleration: 50.0
    angular.z.min_acceleration: -50.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0

    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
