<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>tuw_spike_description</name>
  <version>1.0.0</version>
  <description>URDF/xacro robot model of the tuw_spike vehicle and its robot_state_publisher launch files.</description>
  <maintainer email="markus.bader@tuwien.ac.at">Markus Bader</maintainer>
  <author email="e12102632@student-tuwien.ac.at">Moritz Taferner</author>
  <author email="markus.bader@tuwien.ac.at">Markus Bader</author>
  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>xacro</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
